name: Main

on: [push]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/lint.yml
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs:
      - lint
      - test